<?php

class Lorem
{
    public static string $small = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tristique odio ac ligula tristique, placerat consequat turpis auctor. Donec tellus ipsum, dapibus id neque vel, posuere vehicula diam. Morbi laoreet tristique ante ac condimentum. In hac habitasse platea dictumst. Integer consequat ultricies eros, in tincidunt purus facilisis sit amet. Integer sed metus a mauris tincidunt feugiat. In gravida congue leo quis finibus. Praesent urna nisi, convallis auctor felis nec, tincidunt dapibus erat. Praesent viverra fringilla mi eu laoreet. Etiam massa urna, consequat a augue in, aliquam consectetur felis. Curabitur mattis non sapien et fermentum. Nunc scelerisque risus non cursus egestas.";
    public static string $medium = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tincidunt quam dapibus turpis tempus luctus. Sed maximus varius facilisis. Aenean id ante nec lorem imperdiet sodales ac ac sem. Nulla eu efficitur urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis molestie leo. Nulla imperdiet sem eu quam suscipit, at posuere augue convallis. Duis consectetur convallis sapien non interdum. Suspendisse egestas nibh vitae faucibus malesuada. Vivamus ex ipsum, ultricies ut quam nec, bibendum tempus tortor. Donec facilisis pulvinar neque vitae rhoncus.
    Morbi nec dolor metus. Nulla laoreet elit nec sagittis sagittis. In vestibulum, massa ac pulvinar tincidunt, enim elit luctus orci, a rhoncus leo velit vel lorem. Aenean nunc quam, varius eget faucibus sed, consectetur quis mi. Aliquam faucibus metus et nisi posuere, quis molestie ipsum lacinia. Pellentesque gravida purus non lobortis vulputate. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras est nunc, porttitor eget quam ac, varius cursus lorem. Mauris rutrum pretium pulvinar.
    Nullam id risus sed erat vestibulum aliquam ut hendrerit tortor. Fusce nisl lorem, molestie in commodo ac, gravida sit amet neque. Sed scelerisque metus at massa aliquam, eget ullamcorper justo dignissim. Donec vel quam mattis, aliquam erat a, pretium metus. Morbi finibus, leo luctus dictum imperdiet, mi felis semper nibh, eu posuere nulla urna ac massa. Donec vehicula dui vehicula, rhoncus massa vel, sagittis mi. Vivamus nisi eros, vestibulum id lorem sit amet, sagittis vulputate ante.";
    public static string $big = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec imperdiet facilisis ante nec pulvinar. Cras bibendum, arcu eu porttitor venenatis, ex felis ornare quam, eget tempus risus arcu a tellus. Morbi id justo ipsum. Vestibulum pulvinar purus non neque luctus, nec facilisis nisi tincidunt. Phasellus justo magna, dignissim eu bibendum non, luctus nec mauris. Vestibulum sit amet tortor libero. Fusce luctus placerat dolor, at semper nisl fermentum ac. Donec dui sapien, volutpat non metus non, tempor tristique libero. Aliquam id sem tortor. Vestibulum rutrum turpis at purus tempus tempus. In sit amet ultricies metus. Curabitur aliquet dignissim volutpat.
    Suspendisse erat felis, vehicula eget mauris ut, tristique luctus urna. Duis tristique, turpis ac laoreet malesuada, quam metus sodales tortor, eu iaculis lacus ex ac felis. Suspendisse finibus finibus pellentesque. Pellentesque rutrum ut mi a pulvinar. Phasellus id eros ligula. Sed accumsan ante tortor, vitae sollicitudin mauris elementum nec. Donec leo metus, auctor a lorem a, elementum porttitor orci. Aliquam quis mi felis. Aenean ut elit quis ligula lacinia lobortis ut ut diam. Nunc dui eros, tempus in odio vitae, gravida dignissim velit.
    In lorem lacus, aliquet a semper et, viverra sed erat. Nullam sagittis luctus ultrices. Fusce dui arcu, imperdiet quis tortor vitae, feugiat placerat metus. Ut tincidunt tellus sit amet enim finibus consectetur. Etiam pharetra condimentum eros, vel egestas odio feugiat at. Cras aliquet eget ligula at vehicula. Proin cursus urna ut ullamcorper blandit. Vestibulum consequat ornare lorem non facilisis. Sed id posuere massa. Aenean pellentesque dignissim dolor. Donec ullamcorper rhoncus lacinia. Nam at nisl in eros fringilla semper.
    Aenean nec magna efficitur quam pellentesque efficitur. Suspendisse nec maximus magna. Sed auctor sem erat, ut imperdiet justo posuere in. Ut efficitur ipsum sit amet ligula viverra accumsan. Donec sit amet posuere lectus. Vestibulum tincidunt pellentesque hendrerit. Morbi eget justo sed ante tempor tempus nec nec purus. Duis id viverra metus, at vehicula dui. Nam felis arcu, lobortis id tristique a, tincidunt et erat. Nam pretium sapien id consectetur elementum.
    Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Fusce sit amet ante blandit, tempus purus sed, ullamcorper ante. Cras accumsan convallis dolor in consequat. Nam et nibh nec nisi consequat rhoncus. Vivamus blandit sit amet felis id sollicitudin. Pellentesque luctus eros id rutrum molestie. Nulla sit amet fringilla purus. Cras at pretium arcu. Aenean pellentesque turpis nec enim luctus consequat.";
}