<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIkm8wfg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIkm8wfg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIkm8wfg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIkm8wfg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIkm8wfg\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ikm8wfg',
    'container.build_id' => '5866d512',
    'container.build_time' => 1695729846,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIkm8wfg');
