<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJBxsExv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJBxsExv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJBxsExv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJBxsExv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJBxsExv\App_KernelDevDebugContainer([
    'container.build_hash' => 'JBxsExv',
    'container.build_id' => 'dc981545',
    'container.build_time' => 1695769520,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJBxsExv');
