<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWpZdM7T\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWpZdM7T/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWpZdM7T.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWpZdM7T\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWpZdM7T\App_KernelDevDebugContainer([
    'container.build_hash' => 'WpZdM7T',
    'container.build_id' => 'fd20b4a4',
    'container.build_time' => 1695723006,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWpZdM7T');
